name: Build, test, and deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: bomar-diesel-services/yarn.lock

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install deps (yarn)
        working-directory: bomar-diesel-services
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: bomar-diesel-services
        run: yarn lint

      - name: Test (Vitest)
        working-directory: bomar-diesel-services
        run: yarn test:run --coverage
        env:
          CI: true

      - name: Build
        working-directory: bomar-diesel-services
        run: yarn build

      - name: Prepare Pages artifacts (CNAME, SPA fallback, nojekyll)
        run: |
          echo "bomar.bluefenix.net" > bomar-diesel-services/dist/CNAME
          touch bomar-diesel-services/dist/.nojekyll
          cp bomar-diesel-services/dist/index.html bomar-diesel-services/dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bomar-diesel-services/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4